### ISSUE TITLE
hi  got problem

### ISSUE THREAD

**Issue by dzzrit** [jcatrysse/redmine_issue_todo_lists2#2] opened 2023-07-15 11:51 UTC
[redmine-1 (1).csv](https://github.com/jcatrysse/redmine_issue_todo_lists2/files/12061283/redmine-1.1.csv)
 

2023/07/15 19:32:15,stdout,    class TodoListsDrop < ::Liquid::Drop

2023/07/15 19:32:15,stdout,

2023/07/15 19:32:15,stdout,NameError: uninitialized constant Liquid

2023/07/15 19:32:15,stdout,rake aborted!

**Comment by dzzrit** [comment] 2023-07-15 11:53
I don't understand code or programming. If you need any more information, please let me know how to obtain it

**Comment by jcatrysse** [comment] 2023-07-15 12:14
Ah I see. It's because you are missing the RedmineUp Reporter plugin or any other plugin depending on liquid for that matter. I didn't think about that… I will resolve that issue when I'm back at work in two weeks.

I'll let you know when it's resolved.

I think that installing that RedmineUp reporter plugin will solve it for now.

**Comment by jcatrysse** [comment] 2023-07-15 13:15
Could you please test? I have no way of testing myself for the moment.

**Comment by dzzrit** [comment] 2023-07-25 08:22
![QQ截图20230725161902](https://github.com/jcatrysse/redmine_issue_todo_lists2/assets/139627296/bae6066a-fbdd-4141-aabb-b7d5b87383ca)

It seems like the problem still exists

**Comment by dzzrit** [comment] 2023-07-25 08:24
Is there a problem with my installation process? or does anyone else install the RedmineUp Reporter plugin?

**Comment by dzzrit** [comment] 2023-07-25 08:25
The RedmineUp Reporter plugin is not free and I cannot bear the cost. Is there any other plugin available to replace it

**Comment by jcatrysse** [comment] 2023-07-25 08:30
No, I will resolve this. The problem is that I don't have a computer at hand until next week, so I cannot test my solution for now.

Could you please verify first what version you are using in the init.rb?

**Comment by dzzrit** [comment] 2023-07-25 08:32
"Could you please verify first what version you are using in the init.rb?"
Does it refer to the version of Redmine?

**Comment by dzzrit** [comment] 2023-07-25 08:36
![image](https://github.com/jcatrysse/redmine_issue_todo_lists2/assets/139627296/4b4f1c3a-a76e-4203-ae26-f1b61355e67c)

**Comment by jcatrysse** [comment] 2023-07-25 08:36
No, the version of the plugin. I suspect you haven't updated to the latest version yet. In the plugin folder, there is a file called: init.rb, when you open it with a text editor you should see the version.

Please make sure you have updated the plugin to the latest version. Remove the plugin entirely and download it again.

**Comment by dzzrit** [comment] 2023-07-25 08:38
![image](https://github.com/jcatrysse/redmine_issue_todo_lists2/assets/139627296/8cc48bda-502e-4a8b-8283-a20899770105)

**Comment by jcatrysse** [comment] 2023-07-25 08:39
That is correct… and you still have the error?

**Comment by dzzrit** [comment] 2023-07-25 08:41
> 这是正确的……但您仍然有错误吗？
Yes, so I doubt if there was an error in my installation method. I executed the bundle and then executed the bundle exec rake redmine: plugins: migrate NAME=redmine_ Issue_ Todo_ Lists2 RAILS_ ENV=production

**Comment by jcatrysse** [comment] 2023-07-25 09:00
Let me think a few minutes about this.

**Comment by jcatrysse** [comment] 2023-07-25 09:11
Could you manually modify your init.rb and replace

``` ruby
if defined?(::Liquid::Drop)
    require File.dirname(__FILE__) + '/lib/redmine_issue_todo_lists/liquid/todo_lists_drop'
    require File.dirname(__FILE__) + '/lib/redmine_issue_todo_lists/patches/issue_drop_patch.rb'
end
```

by

``` ruby
if defined?(::Liquid::Drop)
  require File.dirname(__FILE__) + '/lib/redmine_issue_todo_lists/liquid/todo_lists_drop'
  require File.dirname(__FILE__) + '/lib/redmine_issue_todo_lists/patches/issue_drop_patch.rb'
else
  liquid_files = [File.dirname(__FILE__) + '/lib/redmine_issue_todo_lists/liquid/todo_lists_drop.rb',
                  File.dirname(__FILE__) + '/lib/redmine_issue_todo_lists/patches/issue_drop_patch.rb']

  Rails.autoloaders.each do |autoloader|
    autoloader.ignore(liquid_files)
  end
end
```

and try again? If it doesn't work you could try this workaround.

The error is stemming from the missing `liquid` gem in the application's environment, but normally in the latest version this should be resolved. `Liquid` is a Ruby library for rendering safe templates which cannot affect the security of the server they are rendered on. In this case, it's required by the `redmine_issue_todo_lists2` plugin, but it's only useful for users already using liquid, so it can be ignored safely.

I will look at this further, but you could try the following, as a workaround:

1. Add the liquid gem to your Redmine's `Gemfile`. Open the Gemfile in a text editor and add this line:

```ruby
gem 'liquid'
```

2. Run the following command to install the gem (in you Redmine folder):

```bash
bundle install
```

3. After the gem is installed, retry the migration command:

```bash
bundle exec rake redmine:plugins:migrate NAME=redmine_issue_todo_lists2 RAILS_ENV=production
```

This should resolve the `uninitialized constant Liquid` error you're encountering.

Please keep me up to date.

In the mean time let me think about the reason behind it.

**Comment by dzzrit** [comment] 2023-07-25 09:15
![QQ截图20230725171025](https://github.com/jcatrysse/redmine_issue_todo_lists2/assets/139627296/f759def4-d88b-4efb-bea4-ca19c38fbe1b)
In your previous answer, you mentioned the lack of liquid, but I don't know what it specifically refers to. so I installed a Redmine CMS plugin related to liquid, and after this plugin is installed, I install Redmine_ Issue_ Todo_lists2 again ,Another error message appeared

**Comment by jcatrysse** [comment] 2023-07-25 09:25
Without my computer at hand I cannot investigate that new issue. The idea you had is good, but it may have introduced a new issue. Related to sqlite, but I'm not sure why.

You could ignore the error and skip the migrate step (the migration was already done).

Or you could remove the CRM plugin and try the things I proposed (modifying init.rb and if it doesn't work, install the liquid gem)

If it doesn't work we will find a solution.

**Comment by dzzrit** [comment] 2023-07-25 09:37
> 如果没有我的电脑，我无法调查这个新问题。你的想法很好，但可能会带来新的问题。与 sqlite 有关，但我不确定为什么。
> 
> 您可以忽略该错误并跳过迁移步骤（迁移已完成）。
> 
> 或者您可以删除 CRM 插件并尝试我建议的操作（修改 init.rb，如果不起作用，请安装 Liquid Gem）
> 
> 如果它不起作用，我们将找到解决方案。
I uninstalled CMS and installed our plugin after restarting, but still reported a
![QQ截图20230725173551](https://github.com/jcatrysse/redmine_issue_todo_lists2/assets/139627296/33e4f322-f101-4e79-9f46-301f1a4e3696)
n error. I will wait for you to fix this issue

**Comment by dzzrit** [comment] 2023-07-25 09:40
> 
I have already modified init.rb

**Comment by jcatrysse** [comment] 2023-07-25 09:44
What SQL are you using? The plugin is probably not compatible with sqlite… you should use MySQL (other SQL has not been tested by me)

I think we are a further step now (that is good news)!

You could probably skip the migrate step. It depends if you are truly using sqlite or not. But I don't know the impact of it, maybe it's just an error you can safely ignore.

Just restart Redmine and see if the plugin is working.

Get back on me on that SQL question. What SQL are you using?

**Comment by dzzrit** [comment] 2023-07-25 09:47
Maybe it sounds silly, but I don't know what database I'm using. I just downloaded Redmine using Docker, configured folder mapping, and started using it

**Comment by jcatrysse** [comment] 2023-07-25 09:54
No worries, we'll see how far we get.
You are probably using SQLite and that's a lightweight database solution, but not ideal.

But we'll see how far we get.

let's see first if the plugin is now somewhat working.

Just restart your Redmine and let's see if we have something. You can (I think) just restart your docker and try.

**Comment by dzzrit** [comment] 2023-07-25 10:09
> 不用担心，我们会看看我们能走多远。 您可能正在使用 SQLite，这是一个轻量级数据库解决方案，但并不理想。
> 
> 但我们会看看我们能走多远。
> 
> 首先让我们看看该插件现在是否可以正常工作。
> 
> 只需重新启动您的Redmine，让我们看看是否有东西。你可以（我认为）重新启动你的d​​ocker并尝试。


[redmine-1.csv](https://github.com/jcatrysse/redmine_issue_todo_lists2/files/12159854/redmine-1.csv)

I have already performed the operation and the plugin cannot run properly. Error code 500 is displayed when viewing the task. I did not do any further testing and the log has been uploaded

**Comment by jcatrysse** [comment] 2023-07-25 10:29
I cannot load the log file in my phone, so it's difficult to identify the exact cause. But:
1. Redmine is starting, so thats good news.
2. I will try to resolve the migration issue, because I assume that's the issue.
3. I think you didn't remove the CMS plugin. You should (if you feel ok with that) remove it to verify if the new code is working fine and that the solution was not only adding the CMS plugin.

I will make some modifications and get back to you.

**Comment by dzzrit** [comment] 2023-07-25 10:47
> 

I don't quite understand. I executed the code to uninstall CMS, removed the CMS folder, restarted Redmine, and then installed List2. If this doesn't remove the CMS plugin, I don't know what to do

It's okay to wait for your reply, or when you get your computer, it's not particularly urgent

**Comment by jcatrysse** [comment] 2023-07-25 11:29
We'll see that next week.

I changed some migration scripts, hoping they are now compatible with all SQL types, using ActiveRecord. But this is experimental for me 😅

Do you know how to `checkout` the updated `2.1.3` branch I just changed? If not I can explain.

Afterward I think you best do these steps:
1. Replace (git pull and git checkout 2.1.3) the current plugin with the new one.
2. Uninstall it (migrate to version 0)
3. Reinstall it (migrate)

Not sure if the second step is necessary or if it will work 😅

**Comment by dzzrit** [comment] 2023-07-25 12:15
Exciting progress! The plugin is ready to use! At the same time, new problems have also emerged, and tasks cannot be displayed in the list.

![image](https://github.com/jcatrysse/redmine_issue_todo_lists2/assets/139627296/0af8ce02-37ae-4814-bc26-a213cff304a3)

![image](https://github.com/jcatrysse/redmine_issue_todo_lists2/assets/139627296/7e50c935-5431-496e-b421-487ca949b307)

**Comment by dzzrit** [comment] 2023-07-25 12:17
[redmine-1 (1).csv](https://github.com/jcatrysse/redmine_issue_todo_lists2/files/12160943/redmine-1.1.csv)

**Comment by jcatrysse** [comment] 2023-07-25 12:41
Could you pull the 2.1.3 branch again and restart Redmine? I made some changes.

The assets were still pointing to the former plugin name.

**Comment by jcatrysse** [comment] 2023-07-25 12:58
It seems I accidentally committed to the master branch directly (thick fingers on a phone keypad).

You can directly take the code from the master branch (default)

**Comment by dzzrit** [comment] 2023-07-25 13:11
There is no error reported, but it seems to conflict with some themes. When using the purplemine2 theme and its variants, it cannot be displayed normally. When using other themes, it can be displayed normally. I don't know how large this range is

**Comment by dzzrit** [comment] 2023-07-25 13:15
I think the problem I encountered has been resolved, only one compatibility issue with certain themes

**Comment by jcatrysse** [comment] 2023-07-25 13:21
That is good news!
I have noticed that most themes other than the basic ones, have multiple issues with multiple plugins. So for the moment it's not a major concern.

I will close the issue but please open another issue if you encounter further issues.

If the theme remains an issue, you can also create a new issue with some more details and screenshots. I'll have a look then in due time.

**Closed as completed by jcatrysse** 2023-07-25 13:21 UTC
Labels: bug
